# This workflow will build a Java project with Maven
# For more information see: https://aberger.at/blog/2021/05/29/cloud-startproject.html

name: Build appsrv with maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '15'
    - uses: actions/checkout@v2
    - name: cache maven repository
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
        key: ${{ runner.os }}-build-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-m2-

    - name: build with Maven
      run: |
        mvn -jar appsrv/target/application-server-0.5.0-runner.jar -Dquarkus-profile=prod -Dbase.href=${{ secrets.BASE_HREF }} -B install
#       mvn -Pnative -Dquarkus.native.container-build=true -Dquarkus-profile=prod -Dbase.href=${{ secrets.BASE_HREF }} -B install
#       jvm build (not optimized for cloud): mvn -Dquarkus-profile=prod -Dbase.href=${{ secrets.BASE_HREF }} -B install
    - name: build docker images
      run: distribution/target/distribution-0.5.0-dist/docker/build.sh build ${{ secrets.REGISTRY_USER }}

    - name: login to LeoCloud
      uses: docker/login-action@v1
      with:
        registry: registry.cloud.htl-leonding.ac.at
        username: ${{ secrets.REGISTRY_USER }}@${{ secrets.REGISTRY_EMAIL_DOMAIN }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: push docker images to LeoCloud
      run: |
        distribution/target/distribution-0.5.0-dist/docker/build.sh push ${{ secrets.REGISTRY_USER }}
#       docker push registry.cloud.htl-leonding.ac.at/${{ secrets.REGISTRY_USER }}/appsrv

    - name: read me
      run: |
        echo "kubectl credentials have not been added to the public repository."
        echo "use kubectl on your workstation now to deploy this service to the cloud"
